{
 "title": "Connected Vehicles",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "#  Connected Vehicles Telemetry Dashboard"
   }
  },
  {
   "title": "Vehicles in Motion",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(vehicles_in_motion)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Warnings",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(warnings)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Car Models",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (model) ({__name__=\"vehicles_in_motion\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Regions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (region) ({__name__=\"vehicles_in_motion\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vehicles in Motion per Region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(region) (vehicles_in_motion)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vehicles in Motion per Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(model) (vehicles_in_motion)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warnings per Region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "sum by(region) (warnings)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Warnings per Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "expr": "sum by(model) (warnings)", "legendFormat": "__auto" }
   ]
  }
 ]
}